# Managed by Komodo
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9925:9000"
    volumes:
      - /mnt/data/mealie/data:/app/data
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      BASE_URL: https://mealie.bkspc.cc
      SMTP_HOST: smtp.startmail.com
      SMTP_PORT: 465
      SMTP_AUTH_STRATEGY: SSL
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_NAME: Backspace
      SMTP_FROM_EMAIL: postmaster@bkspc.cc
